---
name: Workflow Restarter
on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      run_id:
        required: true
        type: string
      # token:
      #   required: true
      #   type: string
    secrets:
      SOURCE_REPO_GITHUB_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      repo:
        description: "GitHub repository name."
        required: true
        type: string
      run_id:
        description: "The ID of the workflow run to rerun."
        required: true
        type: string
      # token:
      #   description: "The ID of the workflow run to rerun."
      #   required: true
      #   type: string
    secrets:
      SOURCE_REPO_GITHUB_TOKEN:
        required: true
jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
    # checkout the repository because I want bundler to have access to my Gemfile
    - name: Checkout repository
      uses: actions/checkout@v2

    # setup ruby including a bundle install of my Gemfile
    - name: Set up Ruby and install Octokit
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3'
        bundler-cache: true # 'bundle install' will be run and gems cached for faster workflow runs

    # bundle exec ruby to pick up the installed Octokit gem
    - name: Get workflow run details with Octokit
      run: |
        bundle exec ruby -e "
        require 'octokit'
        client = Octokit::Client.new(:access_token => '${{ secrets.SOURCE_REPO_GITHUB_TOKEN }}')
        repo = '${{ inputs.repo }}'
        run_id = '${{ inputs.run_id }}'
        response = client.workflow_run(repo, run_id)
        puts 'Run attempts: ' + response[:run_attempt].to_s
        if response[:run_attempt] < 4
          client.rerun_workflow_run(repo, run_id)
        end
        "
