name: Workflow Restarter

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "GitHub repository name."
        required: true
        type: string
      run_id:
        description: "The ID of the workflow run to rerun."
        required: true
        type: string
      retries:
        description: "The number of times to retry the workflow run."
        required: false
        type: string
        default: "3"

jobs:
  call-reusable-workflow:
    uses: "gavindidrichsen-puppetlabs/github_actions_reusable/.github/workflows/workflow-restarter-implementation.yml@main"
    with:
      repo: ${{ inputs.repo }}
      run_id: ${{ inputs.run_id }}
      retries: ${{ inputs.retries }}
